title: The Tech Chronicle
author:
  email: 'info@byteme.in'
description: Where knowledge is shared

# Build settings
plugins:
  - jekyll-feed
  - jekyll-remote-theme

remote_theme: jonaharagon/jekyll-bootstrap-theme
# Theme configuration information: https://github.com/jonaharagon/jekyll-bootstrap-theme

excerpts:
  show: true
  auto_truncate: true

bootstrap:
  social_links:
    twitter: 'https://twitter.com/akshobg'
    github:  'https://github.com/akshob'